extracting grammars from language documents and collecting them
git-svn-id: https://slps.svn.sourceforge.net/svnroot/slps@789 ab42f6e0-554d-0410-b580-99e487e6eeb2

diff --git a/shared/tools/pdf2bgf b/shared/tools/pdf2bgf
--- a/shared/tools/pdf2bgf
+++ b/shared/tools/pdf2bgf
@@ -7,7 +7,7 @@ cd ../..
 SLPS=${PWD}
 cd ${LOCAL1}
 
-if [ $# -lt 2 ]; then
+if [ $# -ne 4 ]; then
     echo "This tool produces a BGF grammar from a grammar copy-pasted from a PDF"
     echo "Usage:"
     echo "        pdf2bgf [<keywords-list>] <input-lll> <output-bgf>"
@@ -15,8 +15,14 @@ if [ $# -lt 2 ]; then
 elif [ ! -r $1 ]; then
     echo "Oops: $1 not found or not readable."
     exit 1
-elif [ $# -eq 2 ]; then
-	python ${SLPS}/topics/extraction/bnf2bgf/pdf2lll.py $1 intermediate.lll
+elif [ ! -r $3 ]; then
+    echo "Oops: $1 not found or not readable."
+    exit 1
+elif [ ! -r $4 ]; then
+    echo "Oops: $1 not found or not readable."
+    exit 1
+else
+	python ${SLPS}/topics/extraction/bnf2bgf/pdf2lll.py $1 intermediate.lll $3 $4
     python ${SLPS}/topics/extraction/bnf2bgf/lll2bgf.py intermediate.lll $2
 	rm -f intermediate.lll
 fi
